package Assignments.Assignment_6.Facade;

import java.util.ArrayList;

public class Main {
    public static void main(String[] args) {
        // books generated by ChatGPT
        Book book1 = new Book(1, "Harry Potter", "J.K. Rowling", false);
        Book book2 = new Book(2, "The Hobbit", "J.R.R. Tolkien", true);

        // Create a user
        ArrayList<Book> userBooks = new ArrayList<>();
        User user = new User("Alice", "alice123", "password", userBooks);

        // Create a library facade
        LibraryFacade facade = new LibraryFacade();

        // Test borrowing a book
        System.out.println("Borrowing a book...");
        boolean borrowed = facade.borrowBook(book1, user);
        if (borrowed) {
            System.out.println("Book borrowed successfully.");
        } else {
            System.out.println("Failed to borrow book. Book not available.");
        }

        // Test returning a book
        System.out.println("\nReturning a book...");
        boolean returned = facade.returnBook(book1, user);
        if (returned) {
            System.out.println("Book returned successfully.");
        } else {
            System.out.println("Failed to return book. User does not have the book.");
        }
    }
}
